package com.osc.backend.service;

import com.osc.backend.dto.EntityRequest;
import com.osc.backend.dto.EntityResponse;
import com.osc.backend.dto.TreeNode;
import com.osc.backend.entity.*;
import com.osc.backend.exception.OscException;
import com.osc.backend.repository.*;
import com.osc.backend.security.JwtUtil;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.stream.Collectors;

@Service
public class OrgEntityService {

    private final OrgEntityRepository orgEntityRepository;
    private final CategoryRepository categoryRepository;
    private final AffiliationRepository affiliationRepository;
    private final GroupRepository groupRepository;
    private final FunctionalCodeRepository functionalCodeRepository;
    private final CodeGenerationService codeGenerationService;
    private final UserRepository userRepository;
    private final JwtUtil jwtUtil;

    public OrgEntityService(OrgEntityRepository orgEntityRepository,
                            CategoryRepository categoryRepository,
                            AffiliationRepository affiliationRepository,
                            GroupRepository groupRepository,
                            FunctionalCodeRepository functionalCodeRepository,
                            CodeGenerationService codeGenerationService,
                            UserRepository userRepository,
                            JwtUtil jwtUtil) {
        this.orgEntityRepository = orgEntityRepository;
        this.categoryRepository = categoryRepository;
        this.affiliationRepository = affiliationRepository;
        this.groupRepository = groupRepository;
        this.functionalCodeRepository = functionalCodeRepository;
        this.codeGenerationService = codeGenerationService;
        this.userRepository = userRepository;
        this.jwtUtil = jwtUtil;
    }

    @Transactional
    public EntityResponse createEntity(EntityRequest request, HttpServletRequest httpRequest) {
        // Validate required fields
        if (request.getName() == null || request.getName().isBlank()) {
            throw new OscException("Name is required.");
        }
        if (request.getLevel() == null || request.getLevel() < 1 || request.getLevel() > 5) {
            throw new OscException("Level must be between 1 and 5.");
        }
        if (request.getCategoryId() == null) {
            throw new OscException("Category is required.");
        }
        if (request.getAffiliationId() == null) {
            throw new OscException("Affiliation is required.");
        }

        int level = request.getLevel();

        // If group is selected, override category from group
        // Group's levelCode is used directly (groups have pre-defined codes)
        Long categoryId = request.getCategoryId();
        String levelCode = null;
        if (request.getGroupId() != null) {
            Group group = groupRepository.findById(request.getGroupId())
                    .orElseThrow(() -> new OscException("Group not found."));
            categoryId = group.getCategoryId();
            levelCode = group.getLevelCode();
        }

        // Load category and affiliation
        Category category = categoryRepository.findById(categoryId)
                .orElseThrow(() -> new OscException("Category not found."));
        Affiliation affiliation = affiliationRepository.findById(request.getAffiliationId())
                .orElseThrow(() -> new OscException("Affiliation not found."));

        // Validate category matches level
        if (!category.getLevel().equals(level)) {
            throw new OscException("Category '" + category.getName() + "' does not match level " + level
                    + ". Expected level " + category.getLevel() + ".");
        }

        // Validate parent
        OrgEntity parent = null;
        if (level == 1) {
            // Level 1 has no parent
            if (request.getParentId() != null) {
                throw new OscException("Level 1 entities must not have a parent.");
            }
            // Level 1 codes are auto-generated by CodeGenerationService
        } else {
            // Level 2-5 must have a parent
            if (request.getParentId() == null) {
                throw new OscException("Parent is required for level " + level + " entities.");
            }
            parent = orgEntityRepository.findById(request.getParentId())
                    .orElseThrow(() -> new OscException("Parent entity not found."));

            // Child level must be greater than parent level
            if (level <= parent.getLevel()) {
                throw new OscException("Child level (" + level + ") must be greater than parent level ("
                        + parent.getLevel() + ").");
            }

            // Check RBAC scope
            checkScope(httpRequest, parent);

            // Auto-generate levelCode if not already set by group
            if (levelCode == null) {
                levelCode = generateNextLevelCode(request.getParentId(), level);
            } else {
                // Group-provided levelCode: validate and check uniqueness
                codeGenerationService.validateLevelCode(levelCode);
                if (orgEntityRepository.existsByParentIdAndLevelAndLevelCode(
                        request.getParentId(), level, levelCode.toUpperCase())) {
                    throw new OscException("Level code '" + levelCode + "' already exists under this parent at level " + level + ".");
                }
            }
        }

        // Validate functional code if provided
        if (request.getFunctionalCodeId() != null) {
            functionalCodeRepository.findById(request.getFunctionalCodeId())
                    .orElseThrow(() -> new OscException("Functional code not found."));
        }

        // Build entity
        OrgEntity entity = OrgEntity.builder()
                .name(request.getName())
                .parentId(request.getParentId())
                .level(level)
                .levelCode(level == 1 ? null : levelCode.toUpperCase())
                .categoryId(categoryId)
                .affiliationId(request.getAffiliationId())
                .groupId(request.getGroupId())
                .functionalCodeId(request.getFunctionalCodeId())
                .build();

        // Generate full code
        String fullCode = codeGenerationService.generateFullCode(entity, parent, category, affiliation);
        entity.setFullCode(fullCode);

        // For Level 1, extract the auto-generated levelCode from fullCode
        if (level == 1) {
            // fullCode format: X1-X2X3-00-00-00-00-X12X13
            String[] parts = fullCode.split("-");
            entity.setLevelCode(parts[1]); // X2X3
        }

        OrgEntity saved = orgEntityRepository.save(entity);
        return toResponse(saved);
    }

    /**
     * Auto-generate the next available level code for a given parent and level.
     * Fetches existing level codes, extracts numeric values, finds the max,
     * and generates the next value formatted as 2 digits (01, 02, ..., 99).
     * Throws an exception if the next value exceeds 99.
     */
    private String generateNextLevelCode(Long parentId, int level) {
        List<String> existingCodes;
        if (parentId == null) {
            existingCodes = orgEntityRepository.findLevelCodesByParentIdIsNullAndLevel(level);
        } else {
            existingCodes = orgEntityRepository.findLevelCodesByParentIdAndLevel(parentId, level);
        }

        // Extract numeric values from existing level codes and find the maximum
        int maxValue = 0;
        for (String code : existingCodes) {
            if (code != null) {
                try {
                    int numericValue = Integer.parseInt(code);
                    if (numericValue > maxValue) {
                        maxValue = numericValue;
                    }
                } catch (NumberFormatException e) {
                    // Non-numeric codes (e.g., from groups) — skip them for numeric sequence
                }
            }
        }

        int nextValue = maxValue + 1;

        if (nextValue > 99) {
            throw new OscException("Maximum level code (99) exceeded for parent ID " + parentId
                    + " at level " + level + ". Cannot create more entities.");
        }

        return String.format(java.util.Locale.US, "%02d", nextValue);
    }

    public List<EntityResponse> getAllEntities(HttpServletRequest httpRequest) {
        List<OrgEntity> allEntities = orgEntityRepository.findAll();

        // Apply scope filtering
        String token = extractToken(httpRequest);
        if (token != null) {
            String role = jwtUtil.extractRole(token);
            Long scopeEntityId = jwtUtil.extractScopeEntityId(token);

            if (!"MINISTRY_ADMIN".equals(role) && scopeEntityId != null) {
                Set<Long> allowedIds = getSubtreeIds(scopeEntityId);
                allowedIds.add(scopeEntityId);
                allEntities = allEntities.stream()
                        .filter(e -> allowedIds.contains(e.getId()))
                        .collect(Collectors.toList());
            }
        }

        return allEntities.stream().map(this::toResponse).collect(Collectors.toList());
    }

    public EntityResponse getEntity(Long id, HttpServletRequest httpRequest) {
        OrgEntity entity = orgEntityRepository.findById(id)
                .orElseThrow(() -> new OscException("Entity not found."));

        checkScope(httpRequest, entity);
        return toResponse(entity);
    }

    public List<TreeNode> getTree(HttpServletRequest httpRequest) {
        List<OrgEntity> allEntities = orgEntityRepository.findAll();

        // Apply scope filtering
        String token = extractToken(httpRequest);
        if (token != null) {
            String role = jwtUtil.extractRole(token);
            Long scopeEntityId = jwtUtil.extractScopeEntityId(token);

            if (!"MINISTRY_ADMIN".equals(role) && scopeEntityId != null) {
                Set<Long> allowedIds = getSubtreeIds(scopeEntityId);
                allowedIds.add(scopeEntityId);
                allEntities = allEntities.stream()
                        .filter(e -> allowedIds.contains(e.getId()))
                        .collect(Collectors.toList());
            }
        }

        // Build tree
        Map<Long, TreeNode> nodeMap = new LinkedHashMap<>();
        for (OrgEntity e : allEntities) {
            Category cat = categoryRepository.findById(e.getCategoryId()).orElse(null);
            Affiliation aff = affiliationRepository.findById(e.getAffiliationId()).orElse(null);

            TreeNode node = TreeNode.builder()
                    .id(e.getId())
                    .name(e.getName())
                    .level(e.getLevel())
                    .levelCode(e.getLevelCode())
                    .fullCode(e.getFullCode())
                    .categoryName(cat != null ? cat.getName() : null)
                    .affiliationName(aff != null ? aff.getName() : null)
                    .children(new ArrayList<>())
                    .build();
            nodeMap.put(e.getId(), node);
        }

        List<TreeNode> roots = new ArrayList<>();
        for (OrgEntity e : allEntities) {
            TreeNode node = nodeMap.get(e.getId());
            if (e.getParentId() == null || !nodeMap.containsKey(e.getParentId())) {
                roots.add(node);
            } else {
                TreeNode parentNode = nodeMap.get(e.getParentId());
                if (parentNode != null) {
                    parentNode.getChildren().add(node);
                }
            }
        }

        return roots;
    }

    @Transactional
    public EntityResponse updateEntity(Long id, EntityRequest request, HttpServletRequest httpRequest) {
        OrgEntity entity = orgEntityRepository.findById(id)
                .orElseThrow(() -> new OscException("Entity not found."));

        checkScope(httpRequest, entity);

        // Update name
        if (request.getName() != null && !request.getName().isBlank()) {
            entity.setName(request.getName());
        }

        // Update affiliation
        if (request.getAffiliationId() != null) {
            affiliationRepository.findById(request.getAffiliationId())
                    .orElseThrow(() -> new OscException("Affiliation not found."));
            entity.setAffiliationId(request.getAffiliationId());
        }

        // Update functional code
        if (request.getFunctionalCodeId() != null) {
            functionalCodeRepository.findById(request.getFunctionalCodeId())
                    .orElseThrow(() -> new OscException("Functional code not found."));
            entity.setFunctionalCodeId(request.getFunctionalCodeId());
        }

        // Update group
        entity.setGroupId(request.getGroupId());

        // Regenerate full code if affiliation changed
        if (request.getAffiliationId() != null) {
            Category category = categoryRepository.findById(entity.getCategoryId())
                    .orElseThrow(() -> new OscException("Category not found."));
            Affiliation affiliation = affiliationRepository.findById(entity.getAffiliationId())
                    .orElseThrow(() -> new OscException("Affiliation not found."));

            OrgEntity parent = entity.getParentId() != null
                    ? orgEntityRepository.findById(entity.getParentId()).orElse(null)
                    : null;

            String fullCode = codeGenerationService.generateFullCode(entity, parent, category, affiliation);
            entity.setFullCode(fullCode);
        }

        OrgEntity saved = orgEntityRepository.save(entity);
        return toResponse(saved);
    }

    @Transactional
    public void deleteEntity(Long id, HttpServletRequest httpRequest) {
        OrgEntity entity = orgEntityRepository.findById(id)
                .orElseThrow(() -> new OscException("Entity not found."));

        checkScope(httpRequest, entity);

        // Check for children
        List<OrgEntity> children = orgEntityRepository.findByParentId(id);
        if (!children.isEmpty()) {
            throw new OscException("Cannot delete entity with children. Delete children first.");
        }

        orgEntityRepository.delete(entity);
    }

    // --- RBAC scope check ---

    private void checkScope(HttpServletRequest httpRequest, OrgEntity entity) {
        String token = extractToken(httpRequest);
        if (token == null) return;

        String role = jwtUtil.extractRole(token);
        Long scopeEntityId = jwtUtil.extractScopeEntityId(token);

        if ("MINISTRY_ADMIN".equals(role)) {
            return; // Full access
        }

        if (scopeEntityId == null) {
            throw new SecurityException("Access denied. No scope assigned.");
        }

        // Check if entity is within scope subtree
        if (!isInSubtree(entity.getId(), scopeEntityId)) {
            throw new SecurityException("Access denied. Entity is outside your scope.");
        }
    }

    private boolean isInSubtree(Long entityId, Long rootId) {
        if (entityId.equals(rootId)) return true;

        OrgEntity current = orgEntityRepository.findById(entityId).orElse(null);
        while (current != null && current.getParentId() != null) {
            if (current.getParentId().equals(rootId)) return true;
            current = orgEntityRepository.findById(current.getParentId()).orElse(null);
        }
        return false;
    }

    private Set<Long> getSubtreeIds(Long rootId) {
        Set<Long> ids = new HashSet<>();
        Queue<Long> queue = new LinkedList<>();
        queue.add(rootId);

        while (!queue.isEmpty()) {
            Long currentId = queue.poll();
            ids.add(currentId);
            List<OrgEntity> children = orgEntityRepository.findByParentId(currentId);
            for (OrgEntity child : children) {
                queue.add(child.getId());
            }
        }
        return ids;
    }

    private String extractToken(HttpServletRequest request) {
        String authHeader = request.getHeader("Authorization");
        if (authHeader != null && authHeader.startsWith("Bearer ")) {
            return authHeader.substring(7);
        }
        return null;
    }

    // --- DTO mapping ---

    private EntityResponse toResponse(OrgEntity entity) {
        Category category = categoryRepository.findById(entity.getCategoryId()).orElse(null);
        Affiliation affiliation = affiliationRepository.findById(entity.getAffiliationId()).orElse(null);

        return EntityResponse.builder()
                .id(entity.getId())
                .name(entity.getName())
                .parentId(entity.getParentId())
                .level(entity.getLevel())
                .levelCode(entity.getLevelCode())
                .fullCode(entity.getFullCode())
                .categoryId(entity.getCategoryId())
                .categoryName(category != null ? category.getName() : null)
                .categoryCode(category != null ? category.getCode() : null)
                .affiliationId(entity.getAffiliationId())
                .affiliationName(affiliation != null ? affiliation.getName() : null)
                .affiliationCode(affiliation != null ? affiliation.getCode() : null)
                .groupId(entity.getGroupId())
                .functionalCodeId(entity.getFunctionalCodeId())
                .build();
    }
}
